"""first_migrate

Revision ID: 8cf358a36021
Revises:
Create Date: 2026-03-25 22:44:11.853213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8cf358a36021"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "platform_channel_id", sa.String(length=128), nullable=False
        ),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "platform_channel_id", name="uq_channel_platform"
        ),
    )
    op.create_index(
        op.f("ix_channels_platform_channel_id"),
        "channels",
        ["platform_channel_id"],
        unique=False,
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("platform_video_id", sa.String(length=128), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "platform_video_id", name="uq_video_platform"
        ),
    )
    op.create_index(
        op.f("ix_videos_channel_id"), "videos", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_videos_platform_video_id"),
        "videos",
        ["platform_video_id"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform_comment_id", sa.String(length=128), nullable=False
        ),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column(
            "parent_platform_comment_id", sa.String(length=128), nullable=True
        ),
        sa.Column("author_id", sa.String(length=128), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "platform_comment_id", name="uq_comment_platform"
        ),
    )
    op.create_index(
        "ix_comments_channel_deleted",
        "comments",
        ["channel_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comments_channel_id"),
        "comments",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comments_platform_comment_id"),
        "comments",
        ["platform_comment_id"],
        unique=False,
    )
    op.create_index(
        "ix_comments_video_active",
        "comments",
        ["video_id", "deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comments_video_id"), "comments", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_video_id"), table_name="comments")
    op.drop_index("ix_comments_video_active", table_name="comments")
    op.drop_index(
        op.f("ix_comments_platform_comment_id"), table_name="comments"
    )
    op.drop_index(op.f("ix_comments_channel_id"), table_name="comments")
    op.drop_index("ix_comments_channel_deleted", table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_videos_platform_video_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_channel_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(
        op.f("ix_channels_platform_channel_id"), table_name="channels"
    )
    op.drop_table("channels")
    # ### end Alembic commands ###
